# Generated by Django 4.2.7 on 2023-11-07 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personifika',
            name='first_name',
            field=models.CharField(max_length=253),
        ),
    ]
